---@meta

---@alias blit_color
---| '0' # white
---| '1' # orange
---| '2' # magenta
---| '3' # light blue
---| '4' # yellow
---| '5' # lime
---| '6' # pink
---| '7' # gray
---| '8' # light gray
---| '9' # cyan
---| 'a' # purple
---| 'b' # blue
---| 'c' # brown
---| 'd' # green
---| 'e' # red
---| 'f' # black

---@generic T
---@class QIT<T>: {[integer]: T}
---@field Insert fun(self:QIT, value:any) Insert a value into the QIT.
---@field n integer The size of the QIT.

---@class button
---@field win table
---@field text string
---@field center_x integer
---@field center_y integer
---@field txt_color colour
---@field bg_color_enable colour
---@field bg_color_disable colour
---@field callback fun()
---@field enabled boolean
---@field displayed boolean
